import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
  createProjectRecord,
  openDatabase,
  updateProjectSelectedPet,
  type DatabaseClient
} from "@/server/db";
import { createSceneClusterRecord } from "@/server/assets/world-assets";
import {
  listAudioAssetRecords,
  REQUIRED_EXPERIENCE_AUDIO_ASSETS
} from "@/server/audio";
import { createGenerationJob } from "@/server/jobs";
import { upsertPetProfileRecord } from "@/server/jobs/pet-analysis/pet-profile-repository";
import { LocalStorageDriver } from "@/server/storage";
import type { ElevenLabsProvider } from "@/server/providers";
import type { JsonValue, PetProfile } from "@/types";
import { handleElevenLabsAudioJob } from "./handler";

let db: DatabaseClient | null = null;
let tmpDir: string | null = null;

afterEach(async () => {
  db?.close();
  db = null;

  if (tmpDir) {
    await fs.rm(tmpDir, { recursive: true, force: true });
    tmpDir = null;
  }
});

describe("handleElevenLabsAudioJob", () => {
  it("stores background music and pet sound effects generated by ElevenLabs", async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "still-with-audio-"));
    db = openDatabase(path.join(tmpDir, "test.sqlite"));
    const storage = new LocalStorageDriver(path.join(tmpDir, "storage"));
    const { project, petProfile } = seedAudioProject(db);
    const provider: ElevenLabsProvider = {
      async composeMusic(input) {
        expect(input.prompt).toContain("Instrumental only");
        return {
          audio: Buffer.from("music"),
          contentType: "audio/mpeg",
          raw: {
            characterCost: null,
            songId: "song-1",
            outputFormat: "mp3_44100_128"
          }
        };
      },
      async createSoundEffect(input) {
        expect(input.text).toContain("No human voice");
        return {
          audio: Buffer.from(`sfx:${input.durationSeconds}`),
          contentType: "audio/mpeg",
          raw: {
            characterCost: "10",
            songId: null,
            outputFormat: "mp3_44100_128"
          }
        };
      }
    };
    const job = createGenerationJob(
      {
        projectId: project.id,
        type: "elevenlabs-audio",
        payload: {
          petProfile: petProfile as unknown as JsonValue
        }
      },
      db
    );

    const result = await handleElevenLabsAudioJob(job, {
      db,
      storage,
      provider
    });
    const assets = listAudioAssetRecords(project.id, db);
    const background = await storage.getObject(
      `projects/${project.id}/audio/background.mp3`
    );

    expect(assets).toHaveLength(REQUIRED_EXPERIENCE_AUDIO_ASSETS.length);
    expect(assets.every((asset) => asset.status === "ready")).toBe(true);
    expect(assets.map((asset) => asset.audioUrl).filter(Boolean)).toHaveLength(
      REQUIRED_EXPERIENCE_AUDIO_ASSETS.length
    );
    expect(background.body.toString("utf8")).toBe("music");
    expect(result).toMatchObject({
      provider: "elevenlabs",
      status: "ready"
    });
  });

  it("records skipped audio assets when ElevenLabs is not configured", async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "still-with-audio-"));
    db = openDatabase(path.join(tmpDir, "test.sqlite"));
    const storage = new LocalStorageDriver(path.join(tmpDir, "storage"));
    const { project } = seedAudioProject(db);
    const job = createGenerationJob(
      {
        projectId: project.id,
        type: "elevenlabs-audio"
      },
      db
    );

    const result = await handleElevenLabsAudioJob(job, {
      db,
      storage,
      provider: null
    });
    const assets = listAudioAssetRecords(project.id, db);

    expect(assets).toHaveLength(REQUIRED_EXPERIENCE_AUDIO_ASSETS.length);
    expect(assets.every((asset) => asset.status === "skipped")).toBe(true);
    expect(assets.every((asset) => asset.audioUrl === null)).toBe(true);
    expect(result).toMatchObject({
      provider: "elevenlabs",
      status: "skipped",
      reason: "missing-api-key"
    });
  });
});

function seedAudioProject(db: DatabaseClient): {
  project: ReturnType<typeof createProjectRecord>;
  petProfile: PetProfile;
} {
  const project = createProjectRecord({ status: "preparing_pet" }, db);
  const petProfile: PetProfile = {
    id: "pet-profile-1",
    projectId: project.id,
    sourceCandidateIds: ["candidate-1"],
    species: "dog",
    name: null,
    traitSummary: "small white dog with brown ears",
    distinctiveMarkings: ["brown ears"],
    faceDescription: "soft face",
    bodyDescription: "small body",
    accessories: [],
    selectionConfidence: 0.93,
    clarificationRequired: false,
    clarificationAnswer: null
  };

  upsertPetProfileRecord(petProfile, db);
  updateProjectSelectedPet(project.id, petProfile.id, db);
  createSceneClusterRecord(
    {
      id: "scene-1",
      projectId: project.id,
      label: "Living room",
      sourceImageIds: [],
      representativeImageIds: [],
      spatialPrompt: "A warm room with afternoon light.",
      status: "ready"
    },
    db
  );

  return { project, petProfile };
}
